### ISSUE TITLE
Commit 25e4518 breaks GLdc

### ISSUE THREAD

**Issue by Corbachu** [Kazade/GLdc#21]
The most recent commit <25e4518> breaks everything under GLdc. Not only the EDGE engine, but the examples too (textures are all messed up). Had to revert to the one before that to make things workable again.

**Comment by Kazade** [comment]
I think what you were hitting was due to some weirdness when using mipmapped compressed textures.

For some reason, if you disable mipmap filtering (e.g. just use GL_LINEAR rather than GL_LINEAR_MIPMAP_LINEAR), the pvr displays something odd and I don't understand why.

For now I've forced mipmapping if you have a compressed + mipmapped texture but I need to talk through these filtering modes with someone who knows the PVR stuff well.
